version: "3"

services:
  fake-wallet-db:
    image: postgres
    container_name: fake-wallet-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fake-wallet
    volumes:
      - db-data:/var/lib/postgresql/data

  fake-wallet:
    image: fake-wallet:test
    container_name: fake-wallet
    depends_on:
      - fake-wallet-db
    restart: always
    ports:
      - 5000:80
    environment:
      - CONFIG=/config.yaml
    volumes:
      - ./config.yaml:/config.yaml
    entrypoint: sh -c "fake-wallet migrate up && fake-wallet run app"

volumes:
  db-data: